### ISSUE TITLE
Discussion: should native Promise be used when it is possible? 

### ISSUE THREAD

**Issue by hjkcai** [liriliri/licia#14]
In some cases I do not want a Promise polyfill so that minimal bundle size is kept. I can make sure that my environment has Promise polyfill correctly. So far I have to make use of build tools to ban the Promise module in licia.

**Comment by surunzi** [comment]
Only a few modules are dependent on Promise module. How do you import licia module?

**Comment by hjkcai** [comment]
No I have not started to use it yet. This is just a question I come up with when I was wandering around licia's docs. 

BTW licia seems lack of promise utils like https://github.com/hjkcai/promise-utils

**Comment by surunzi** [comment]
Not all utils will be included, only the popular ones(with huge number of npm downloads) or those I personally consider to be useful.
