### ISSUE TITLE
不知道算不算问题，node全局对象会被打进包里

### ISSUE THREAD

**Issue by iocdacc** [liriliri/licia#18]
虽然可以通过webpack配置忽略掉node全局对象 :smile:

**Comment by surunzi** [comment]
推荐按文件引入，每个模块相当于小型 npm 包。

**Comment by iocdacc** [comment]
其实我看了按文件引入 里面也存在这样的代码：
`crypto = require('crypto');`

如果打包的话 webpack一样会polyfill然后放入包内

**Comment by surunzi** [comment]
按文件引入应该不会，你引了哪个文件？

**Comment by surunzi** [comment]
https://github.com/webpack/webpack/issues/8826

**Comment by iocdacc** [comment]
webpack 会模拟node的crypto 模拟代码高达几百KB
建议在package.json里配置"browser"属性来规定浏览器的入口然后将node的代码去掉

**Comment by surunzi** [comment]
@iocdacc browser 属性已经配置了，你在 webpack 中直接引用 licia 就只会包含那些能在浏览器运行的模块。这里的情况无法用这样来解决，详情见我上面引用的 issue，目前看来可以用`eval('require')('foo')` 暂时解决。

**Comment by surunzi** [comment]
强行使用 browser 配置就必须将原有的一个代码文件分成两份，同时抽离共用部分，最终变成三份，完全没必要。

**Comment by iocdacc** [comment]
```
"main": "./node.js",
"browser": "./browser.js"
```
其实入口已经有两个了。 只需区分一下代码。不过可能会改比较多  确实eval的方法修改比较少
