### ISSUE TITLE
[Security] ReDoS

### ISSUE THREAD

**Issue by ready-research** [liriliri/licia#25]
Hi @surunzi, I have reported a ReDoS issue in huntr
https://www.huntr.dev/bounties/7b9ef50a-3d1d-490a-8fa4-f1ec5e3d3bbf/

Please validate and let us know your opinion on this. Thank you.

**Comment by ready-research** [comment]
@surunzi Reported another issue in huntr
https://www.huntr.dev/bounties/a9f33039-addf-45b1-bf92-d7e3d9b2abc1/

Please validate and let us know your opinion on this. Thank you.

**Comment by surunzi** [comment]
Fixed.
