### ISSUE TITLE
在线builder工具，能否支持全选？

### ISSUE THREAD

**Issue by hyingreborn** [liriliri/licia#6]
还没找到哪里可以下载完整包，懒得自己编译了，在线builder是否能提供一个全选，方便下载完整包使用？

**Comment by hyingreborn** [comment]
手动遍历Dom拿到的，方便其他人：
$ $attr $class $css $data $event $insert $offset $property $remove $safeEls $show Blob Class Color Dispatcher Emitter Enum JsonTransformer LinkedList LocalStore Logger MutationObserver Promise Queue ReduceStore Select SessionStore Stack State Store Tween Url Validator abbrev after ajax allKeys arrToMap atob average base64 before bind btoa bubbleSort callbackify camelCase capitalize castPath centerAlign char chunk clamp className clone cloneDeep cmpVersion compact compose compressImg concat contain convertBase cookie copy createAssigner createUrl cssSupports curry dateFormat debounce debug decodeUriComponent defaults define defineProp delay delegate detectBrowser detectOs difference dotCase download each easing endWith escape escapeJsStr escapeRegExp evalCss evalJs every extend extendDeep extendOwn extractBlockCmts extractUrls fetch fibonacci fileSize fill filter find findIdx findKey findLastIdx flatten fnParams format fraction freeze freezeDeep gcd getUrlParam has hotkey hslToRgb identity idxOf indent inherits insertionSort intersect intersectRange invert isAbsoluteUrl isArgs isArr isArrBuffer isArrLike isBlob isBool isBrowser isBuffer isClose isDataUrl isDate isEl isEmail isEmpty isEqual isErr isEven isFile isFinite isFn isGeneratorFn isInt isJson isLeapYear isMatch isMiniProgram isMobile isNaN isNative isNil isNode isNull isNum isNumeric isObj isOdd isPlainObj isPrimitive isPromise isRegExp isRelative isRetina isStr isStream isTypedArr isUndef isUrl isWindows jsonp kebabCase keyCode keys last lazyRequire linkify loadCss loadImg loadJs longest lowerCase lpad ltrim map mapObj matcher max memStorage memoize meta methods min mkdir moment ms negate nextTick noop normalizePath now objToStr omit once optimizeCb orientation pad pairs parallel parseArgs partial pascalCase perfNow pick pluck precision prefix promisify property query raf random randomBytes range ready reduce reduceRight reject remove repeat restArgs rgbToHsl rmCookie rmdir root rpad rtrim safeCb safeDel safeGet safeSet safeStorage sample scrollTo selectionSort shuffle size slice snakeCase some spaceCase splitCase splitPath startWith strHash stringify stripAnsi stripCmt stripColor stripHtmlTag sum template throttle through timeAgo timeTaken toArr toBool toDate toEl toInt toNum toSrc toStr topoSort trigger trim tryIt type ucs2 unescape union uniqId unique unzip upperCase upperFirst use utf8 uuid values viewportScale waterfall workerize wrap zip

**Comment by surunzi** [comment]
里面包含了只在浏览器端跟只在 Node 端才能跑的模块，全部包含进去运行可能不会正常，晚点提供两个端构建全部模块的快捷方式。

**Comment by surunzi** [comment]
已支持全选，在线生成工具下边模块点击最前面的 allBrowser 和 allNode 就可以自动填写各自平台的所有模块。
